### ISSUE TITLE
Rebasing on latest TinyUSB?

### ISSUE THREAD

**Issue by burtonrodman** [rppicomidi/pico-usb-midi-processor#2]
I know this isn't exactly the right place, but wasn't sure how else to contact you.

Thanks so much for your work on implementing midihost in TinyUSB.  My project wouldn't be possible without this effort.

I'm hoping to update my pico-sdk to version 1.5.0, which of course would be a much newer version of TinyUSB.

I'm happy to do the work of rebasing the midihost branch, but wanted to chat with you first about any known issues, anything that's changed from a architectural perspective in TinyUSB that would change how we'd approach implementing the midi host.

I recall reading something about the bulk transfer something something now being implemented that would affect.

Any thoughts or input would be greatly appreciated!

**Comment by rppicomidi** [comment]
@burtonrodman The pico-sdk uses tinyusb as a submodule. If you don't need to use the tinyusb version that ships with the pico-sdk, you can continue to use the version of tinyusb you are using now. Just use git pull to update the pico-sdk and don't update the tinyusb git submodule. If you are using a Pico W, you will probably want to update the other git submodules.

**Comment by rppicomidi** [comment]
@burtonrodman I know this is an old issue, but I wanted to mention I am trying to get away from using a fork of TinyUSB. Please see the latest revision of this project for the application usb_midi_host driver and the simple patch to TinyUSB. If you want to maintain a fork, please use the latest code to update your fork. Does this response solve your issue?

**Comment by burtonrodman** [comment]
great!  i’ll take a look.  unfortunately my project has been on the back burner and when i pick it back up, i’m sure i’ll be trying to update all the things and this should hopefully make that easier.

**Comment by rppicomidi** [comment]
OK. I will close this issue. If you see a need to revisit the fork, please re-open it.
